### ISSUE TITLE
Plugin doesn't seem to honor env vars

### ISSUE THREAD

**Issue by asachs01** [sensu-plugins/sensu-plugins-victorops#32]
Dropping this in https://sensucommunity.slack.com/archives/C68LV5M9U/p1576173807165800 and also https://sensucommunity.slack.com/archives/C68LV5M9U/p1576082292124700. I thought that I'd tested this, but am now second-guessing myself on the changes in 36d60032c68d837739adc76207560d99e0e968a1

**Comment by jspaleta** [comment]
So far my testing indicates envvars are working,.
But i'm releasing 3.0.0 now that has some changes to help here.

1.. better usage message 
2.. a dryrun mode that can be used to help diagnose problems with envvar if they occur

**Comment by jspaleta** [comment]
re-open if there's more info from using 3.0.0
