### ISSUE TITLE
create new release with updated victorops.rb

### ISSUE THREAD

**Issue by oryband** [sensu-plugins/sensu-plugins-victorops#4]
the current release (0.0.3) doesn't include the latest changes, and a new one needs to be released

**Comment by oryband** [comment]
@bolshoy

**Comment by MattHodge** [comment]
+1

**Comment by eheydrick** [comment]
[0.1.0](https://rubygems.org/gems/sensu-plugins-victorops/versions/0.1.0) has been released.
